# Authentication and Authorization in Kubernetes
# Authentication is the process of verifying the identity of a user or service trying to access the Kubernetes cluster.
# Authorization is the process of determining what actions an authenti cated user or service is allowed to perform within the cluster.
# Kubernetes supports several authentication methods, including:

### AUTHENTICATION == Loggin In
### AUTHORIZATION == Permissions/ RBAC

# 1. Client Certificates: Users can authenticate using TLS client certificates.
# 2. Bearer Tokens: Users can authenticate using bearer tokens, such as JSON Web Tokens (JWT).
# 3. OpenID Connect (OIDC): Kubernetes can integrate with OIDC providers for authentication.
# 4. Service Accounts: Kubernetes provides service accounts for pods to authenticate with the API server.
# Authorization in Kubernetes can be managed using different mechanisms, including:
# 1. Role-Based Access Control (RBAC): RBAC allows you to define roles

# kubectl create sa my-service-account and bind them to users or service accounts to control access to resources.
# # kubectl get sa > by default service account is created in each namespace and dont have authentication system

## CLUSTER ROLE --> can access resources across all namespaces(cluster-wide/ entire cluster)
## ROLE --> can access resources within a specific namespace(specific namespace only)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole 
metadata:
  name: reader 
rules: 
  - apiGroups: [""] # "" indicates the core API group
    resources: ['pod',"deployments"] 
    verbs: ['get', 'list', 'watch'] # what can you do with the resources

## to apply role to user/service account we need to create rolebinding/ clusterrolebinding
--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
  - kind: ServiceAccount # can be User, Group, ServiceAccount
    name: rg  # name of the user/ service account
    apiGroup: "" 
    namespace: default # namespace of the service account
roleRef:
  kind: ClusterRole
  name: reader # name of the role/ clusterrole
  apiGroup: rbac.authorization.k8s.io


## give deployment access to service account , so that pods created by deployment can use the service account
--- 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: new-deployment
spec:
  serviceAccountName: rg
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: nginx-container
        image: nginx 