# HPA --> horizontal pod autoscaler
# automatically scales the number of pods in a deployment, replica set, or stateful set based
# on observed CPU utilization or other select metrics.
# It helps ensure that your application can handle varying levels of traffic by adjusting the number of running pods accordingly.

#>  Imperative --> kubectl autoscale deployment <deployment-name> --min=<min-pods> --max=<max-pods> --cpu-percent=<target-cpu-utilization>
#> kubectl autoscale deployment myapp-deployment --min=2 --max=10 --cpu-percent=80
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      editor: vscode
  replicas: 2
  template:
    metadata:
      labels:
        editor: vscode
    spec:
      containers:
      - name: new-ctr
        image: nginx:latest
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

# sudo apt install hey
# hey -z 5m -q 10 -c 2 http://<node-ip>:<node-port>
# kubectl expose deployment myapp-deployment --type=NodePort --port=80
# minikube service myapp-deployment --url

## VPA --> vertical pod autoscaler
# automatically adjusts the CPU and memory requests and limits for the containers in your pods
# based on their actual resource usage.
# It helps ensure that your application has the right amount of resources to operate efficiently without over-pro
#visioning or under-provisioning.
# Note: VPA and HPA cannot be used together on the same deployment.
#> kubectl apply -f vpa.yaml
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: myapp-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       myapp-deployment
  updatePolicy:
    updateMode: "Auto"      
  resourcePolicy:   
    containerPolicies:
    - containerName: "new-ctr"
      minAllowed:
        cpu: "200m"
        memory: "256Mi"
      maxAllowed:
        cpu: "1"
        memory: "1Gi" 
      