# A secret is an object that contains a small amount of sensitive data such as a password, a token, or a key.
# Such information might otherwise be put in a Pod specification or in an image.
# Secrets are similar to ConfigMaps, but are specifically intended to hold sensitive information /confidential data.
# They are encoded in base64 to provide a basic level of security.
# they are not good for storing large amounts of data.
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
type: Opaque
data:
  username: aGVsbG8K
  # Example:
  # password: {{ .Values.password | b64enc }}
  password: cGFzc3dvcmQK

--- 

# Now to use this secret in a pod, we can reference it in the pod spec.
apiVersion: v1
kind: Pod
metadata:           
  name: mypod
  namespace: default
spec:
  containers:
    - name: mycontainer
      image: myimage:latest
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
  restartPolicy: Always 

# kubernetes secrets are stored in etcd and are accessible to any user with access to the API server.
# To enhance security, consider using tools like HashiCorp Vault or AWS KMS for managing
# stored in plain base64 encoding.